In [1]:
from keras.datasets import mnist
from keras.models import Model
from keras.layers import Input,Dense
from keras.optimizers import SGD,Adam
import numpy as np
import keras

Using TensorFlow backend.


In [2]:
lr = 0.1
wd = 0.001
num_classes = 10
batch_size = 128
num_epochs = 5

In [3]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [5]:
num_pixels = X_train.shape[1] * X_train.shape[2]
num_pixels

784

In [6]:
X_train = X_train.reshape(X_train.shape[0], num_pixels)
X_test = X_test.reshape(X_test.shape[0], num_pixels)
X_train = X_train/255
X_test = X_test/255

In [7]:
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)

In [8]:
y_train.shape

(60000, 10)

In [9]:
X_train.shape

(60000, 784)

In [10]:
input_img = Input(shape =(784,))
dense1 = Dense(512, activation="relu")(input_img)
dense2 = Dense(512, activation="relu")(dense1)
dense3 = Dense(512, activation="relu")(dense2)
dense4 = Dense(512, activation="relu")(dense3)
output = Dense(10,activation="sigmoid")(dense4)
model = Model(input_img,output)
sgd = SGD(lr=lr, decay=1e-3, momentum=0.9, nesterov=True, clipvalue=5.0)
model.compile(loss=keras.losses.categorical_crossentropy,metrics=['accuracy'],optimizer=sgd)

In [11]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 784)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 512)               401920    
_________________________________________________________________
dense_2 (Dense)              (None, 512)               262656    
_________________________________________________________________
dense_3 (Dense)              (None, 512)               262656    
_________________________________________________________________
dense_4 (Dense)              (None, 512)               262656    
_________________________________________________________________
dense_5 (Dense)              (None, 10)                5130      
Total params: 1,195,018
Trainable params: 1,195,018
Non-trainable params: 0
_________________________________________________________________


In [12]:
model.fit(X_train, y_train, 
nb_epoch=num_epochs, 
batch_size=batch_size, 
shuffle=True, 
validation_data=(X_test, y_test))

C:\Program Files\Anaconda3\lib\site-packages\ipykernel\__main__.py:5: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.


Train on 60000 samples, validate on 10000 samples
Epoch 1/5
60000/60000 [==============================] - 23s - loss: 0.3268 - acc: 0.9013 - val_loss: 0.1075 - val_acc: 0.9686

In [13]:
ans =np.argmax(model.predict(X_test),axis=1)

In [14]:
ans.shape

(10000,)

In [15]:
ans

array([7, 2, 1, ..., 4, 5, 6], dtype=int64)

In [16]:
ans[1:5]

array([2, 1, 0, 4], dtype=int64)

In [17]:
y_test[1:5]

array([[ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.]])